# Generated by Django 5.2.7 on 2025-10-10 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
                ('ano_lanzamiento', models.IntegerField()),
                ('director', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('elenco', models.TextField()),
                ('codigo_hash', models.CharField(editable=False, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('texto_resena', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='peliculas.pelicula')),
            ],
        ),
    ]
